<a href="https://colab.research.google.com/github/tanmaykhanna07/python-for-data-science/blob/main/PandasAndNumpyPractice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [6]:
np.random.seed(42)
num_rows = 10000

# Generate 10,000 rows of banking transactions
df_bank = pd.DataFrame({
    "Transaction_ID": range(100000, 100000 + num_rows),
    "Amount": np.round(np.random.exponential(scale=50, size=num_rows) + 5, 2),
    "Location": np.random.choice(["Mumbai", "Delhi", "Bangalore", "Chennai", "Pune"], size=num_rows),
    "Account_Age_Days": np.random.randint(1, 3650, size=num_rows),
    "Device": np.random.choice(["Mobile", "Desktop", "Tablet"], size=num_rows, p=[0.7, 0.25, 0.05])
})

# Inject a "Fraud" flag: True if the amount is high AND the account is brand new
df_bank["Is_Fraud"] = ((df_bank["Amount"] > 150) & (df_bank["Account_Age_Days"] < 30))

print("Total Rows:", len(df_bank))
df_bank.head()

Total Rows: 10000

   Transaction_ID  Amount   Location  Account_Age_Days   Device  Is_Fraud
0          100000   28.46    Chennai               319  Desktop     False
1          100001  155.51      Delhi              3196   Mobile     False
2          100002   70.84       Pune              1396  Desktop     False
3          100003   50.65  Bangalore              1375   Mobile     False
4          100004   13.48  Bangalore              1347  Desktop     False

In [8]:
frauds = df_bank[df_bank['Is_Fraud'] == True]
print("Total Frauds: ", len(frauds))

Total Frauds:  6

In [9]:
mean_amount_by_city = df_bank.groupby('Location')['Amount'].mean()
mean_amount_by_city

Location
Bangalore    54.770660
Chennai      53.369821
Delhi        53.187802
Mumbai       53.309901
Pune         54.830232
Name: Amount, dtype: float64

In [10]:
high_desktop_trans = df_bank[(df_bank['Device'] == "Desktop") & (df_bank['Amount'] > 300) ]
high_desktop_trans

      Transaction_ID  Amount   Location  Account_Age_Days   Device  Is_Fraud
4256          104256  309.83       Pune              2442  Desktop     False
5561          105561  308.14  Bangalore              3635  Desktop     False
5788          105788  371.95     Mumbai              3165  Desktop     False
9345          109345  327.56  Bangalore               209  Desktop     False
9927          109927  385.57       Pune              2295  Desktop     False